### PR TITLE
Feat/add datepicker tank status

### LINKED ISSUE #16: add datepicker to tank status and display on info panel
Joe requested that we add a datepicker to the `Update Action` tab and that the data is reflected in the info tab.
image

### PR DESCRIPTION
**Pull request by baileysingleton**
closes #16

### CODE REVIEW

**Comment by baileysingleton** [comment]
Having some issues with getting the timezone right. If you check it out, the "Updated on" format is wack and the wrong time. Could use some eyes on this!

**Comment by brennand97** [comment]
You just needed to format the date as it was read into state.  I also isolated the task from the view through the `tankInfo` object like everything else.

**Comment by baileysingleton** [comment]
The only thing I don't like is how close the "Action Updated On" text is to the datetime, but I'm apparently **very** bad at changing that table padding

**Comment by danvanhorn** [comment]
This looks great, I changed the time format to 12 hr time rather than 24 hrs and I added am/pm. I'm going to merge this into production right now. Great job @baileysingleton and @brennand97 for getting this done quickly

**Pull request merged**
